// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/version": {
            "get": {
                "description": "Get app version info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "Get app version info",
                "responses": {
                    "200": {
                        "description": "{'latestVersion: 1.0.0', 'requiredVersion': '1.0.0'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/equip": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "equip list for personal user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equip"
                ],
                "summary": "equip list",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/equip.equipListResponse"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "create equip for personal user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equip"
                ],
                "summary": "create equip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "equip name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "note for equip",
                        "name": "note",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "image for equip",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'create success', 'id' : '1'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/equip/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "delete equip for personal user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equip"
                ],
                "summary": "delete equip",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "equip id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'deleted success'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "update equip for personal user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equip"
                ],
                "summary": "update equip",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "equip id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "note",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "image for equip",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'create success'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/equip/{id}/weight": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "update equip weight for personal user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equip"
                ],
                "summary": "update equip weight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "equip id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "note for equip",
                        "name": "weights",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/equip.weightForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'create success'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/forget-password": {
            "post": {
                "description": "user forget password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "forget password",
                "parameters": [
                    {
                        "description": "forgetPassword",
                        "name": "forgetPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ForgetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"forget password success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{\"message\": \"查無此 email\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Logs in a user with the provided email and password, and generates a JWT token for the user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'login success', 'token': 'JWT token', 'reset': '0'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '帳號或密碼錯誤', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/google/access-token": {
            "post": {
                "description": "Logs in a user with the google oauth2 access token, and generates a JWT token for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user with google oauth2 access token",
                "parameters": [
                    {
                        "description": "LoginWithGoogleAccessTokenForm",
                        "name": "LoginWithGoogleAccessTokenForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginWithGoogleAccessTokenForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'login success', 'token': 'JWT token'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/record": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "record list for personal user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "record list",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/record.listResponse"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "create record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "create record",
                "parameters": [
                    {
                        "description": "createBody",
                        "name": "createBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/record.createBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'create success', 'id' : '1'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/record/day-summary": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "record list for personal user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "day summary list",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/record.dateSummaryListResponse"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/record/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "delete record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "delete record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "record id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'delete success'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "update record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "update record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "record id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "updateBody",
                        "name": "updateBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/record.updateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{'message': 'update success', 'id' : '1'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{'message': 'jwt token error', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{'message': '缺少必要欄位', 'error': 'error message'}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "user register",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "register",
                "parameters": [
                    {
                        "description": "registerForm",
                        "name": "registerForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"register success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{\"message\": \"信箱尚未驗證\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"message\": \"register failed\", \"error\": \"server error\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reset-password": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "user reset password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "resetPassword",
                        "name": "resetPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"密碼修改成功\", \"token\": \"jwt token\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "{\"message\": \"密碼修改失敗\", \"error\": \"密碼不一致\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ForgetPassword": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "auth.LoginWithGoogleAccessTokenForm": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.ResetPassword": {
            "type": "object",
            "required": [
                "confirmPassword",
                "newPassword",
                "password"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.registerForm": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "equip.equipExpand": {
            "type": "object",
            "properties": {
                "equip": {
                    "$ref": "#/definitions/models.Equip"
                },
                "lastRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equip.recentRecord"
                    }
                },
                "maxVolumeRecord": {
                    "$ref": "#/definitions/equip.lastMaxWeightRecord"
                },
                "maxWeightRecord": {
                    "$ref": "#/definitions/equip.maxWeightRecord"
                }
            }
        },
        "equip.equipListResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equip.equipExpand"
                    }
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "equip.lastMaxWeightRecord": {
            "type": "object",
            "properties": {
                "dayVolume": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "maxWeight": {
                    "type": "number"
                },
                "maxWeightReps": {
                    "type": "integer"
                }
            }
        },
        "equip.maxWeightRecord": {
            "type": "object",
            "properties": {
                "dayVolume": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "reps": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "equip.recentRecord": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "note": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reps": {
                    "type": "integer"
                },
                "sets": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "equip.weightForm": {
            "type": "object",
            "required": [
                "weights"
            ],
            "properties": {
                "weights": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "models.Equip": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "weights": {
                    "type": "string"
                }
            }
        },
        "record.createBody": {
            "type": "object",
            "required": [
                "equip_id",
                "reps",
                "weight"
            ],
            "properties": {
                "equip_id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "record.dateGroup": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "equips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/record.equipGroup"
                    }
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "record.dateSummaryListResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/record.dateGroup"
                    }
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "record.equip": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "record.equipGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/record.recordDetail"
                    }
                }
            }
        },
        "record.listResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/record.record"
                    }
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "record.record": {
            "type": "object",
            "properties": {
                "equip": {
                    "$ref": "#/definitions/record.equip"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "sets": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "record.recordDetail": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "note": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reps": {
                    "type": "integer"
                },
                "sets": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "record.updateBody": {
            "type": "object",
            "required": [
                "equip_id",
                "reps",
                "weight"
            ],
            "properties": {
                "equip_id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type Bearer followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "scopes": {
                "write": " Grants write access"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
